### ISSUE TITLE
Add basic JSON support

### ISSUE THREAD

**Issue by Andre601** [bergerhealer/BKCommonLib#102]
It was discussed in https://github.com/bergerhealer/TrainCarts/pull/372 to implement a (basic) JSON library to BKCommonLib for features such as hiding the long (and ugly) GitHub URL to make issues behind some normal text.

I believe this could indeed be useful on more than one place. The issue command would just be one possible options.
Additionally could BKCommonLib add support to click a sub-command in a plugin's command lust, to get it suggested into the text box of the player alongside a hover message that could give a more in-depth description about what the command does, its syntax and what arguments/values it supports.

I see a big potential in here.

You could perhaps adobt some of [JSONMessage](https://github.com/Rayzr522/JSONMessage)'s features and tweak those to fit your general need.
The Bukkit/Spigot API for sure wouldn't be a good option and should be avoided (But knowing you would you not touch that at all)

**Comment by bergerkiller** [comment]
I agree, this could also offer support such as showing a WIKI article link when placing down signs, and so on. Some integration in the Localization API would also be helpful, so that users can embed their own links in the text messages configured there.

**Comment by bergerkiller** [comment]
While it's not "json support", this adds support for:
- Clickable links that lead to a URL or copy content onto your clipboard
- Hover tooltips for text
- Some basic append() logic to build messages
- Sending the ChatText to players

https://github.com/bergerhealer/BKCommonLib/commit/815bea4e1f15377c3c039641df18650ba6c38f49

**Comment by Andre601** [comment]
Nice thing. Sure will help improve the plugins in the long run. Especially commands like `/tc issue`
