### ISSUE TITLE
Failed to compile method body, cannot find constructor

### ISSUE THREAD

**Issue by x1p** [bergerhealer/BKCommonLib#103]
##### Spigot version: Purpur 1.16.1

<hr>

#### Problem or bug:
Using Paper, all starts fine
But I run Purpur, a Paper fork and this gives this error: https://pastebin.com/raw/grhpK0RR
I think BKCommonLib has some check to see which server type it runs on and fails to see purpur as a fork of Paper.
It would be nice if BKCommonLib could determine Purpur just as well as it would run on Paper.
BKCommonLib seems to work fine even with this error. I only need this in order to use LightCleaner

#### Expected behaviour:
Preferable no error :)

#### Steps to reproduce:
Run on Paper, no error
Run on Purpur, error
Purpur is a fork of Paper which combines Paper and Tuinity
Purpur can be downloaded here: https://ci.pl3x.net/job/Purpur/

**Comment by Andre601** [comment]
What does Purpur change compared to Paper?

**Comment by Andre601** [comment]
The fact you use a paper fork and that the creators of it claim some of the changes being "too wild" tells me that this server maybe contains changes that may break stuff in TC and BKCommonLib, so berger would probs require to implement separate support for it.

**Comment by bergerkiller** [comment]
Purpur changes quite a lot, but I do officially support it, so I'll have to look into this. It works on Tuinity though.

**Comment by bergerkiller** [comment]
Should be fixed now (tested latest build #673) https://github.com/bergerhealer/BKCommonLib/commit/6226dc6afd3404d727aca07f3f8416741e8f64e5

**Comment by x1p** [comment]
Thank you. Works perfectly.
Meanwhile the dev of Purpur gave me the hint that
`net.pl3x.purpur.PurpurWorldConfig purpurConfig = new net.pl3x.purpur.PurpurWorldConfig("DUMMY", paperConfig, spigotConfig);`
needs to be:
`net.pl3x.purpur.PurpurWorldConfig purpurConfig = new net.pl3x.purpur.PurpurWorldConfig("DUMMY");`
because of updated reflection.

**Comment by bergerkiller** [comment]
Yeah that's what I changed in the commit, and also what I saw looking at the decompiled server source
