### ISSUE TITLE
Can't create a entity??

### ISSUE THREAD

**Issue by ChefBierfles** [bergerhealer/BKCommonLib#106]
##### Spigot version: Paper spigot build 189 (Latest for 1.16.2)

<hr>

#### Problem or bug: I cannot seem to create an player entity it throws an error and i've tried multiple spigot / commonlib versions. 

Error message: https://pastebin.pl/view/23ce8055
Code: https://pastebin.pl/view/a1848c0c. PlayerQuitHandler is called when a player drops an item (Debug purposes)

Thanks in advance! I really can't wrap my head arround it.

**Comment by bergerkiller** [comment]
What type of entity are you creating? Creating (hooked) entity players is not something that works I think

**Comment by Hotseflots** [comment]
Yeah Entity players seems broken. Once I change the EntityType to something like a villager it works flawless. Thanks in advance!

**Comment by bergerkiller** [comment]
Since all I really use it for are minecart entities, it's not something that is being tested a lot. But it's good to document issues like this. I don't think I can make hooked player entities work, since they require a lot of extra logic, like the network connection and stuff.

**Comment by bbayu123** [comment]
Closing issue, yes it's not possible.
