### ISSUE TITLE
Illegal reflective access operation has occured

### ISSUE THREAD

**Issue by 0-0-6** [bergerhealer/BKCommonLib#107]
##### Light Cleaner version: 1.16.3-v1

<hr>

#### Problem or bug:

running a paper-mc server I get the following warning  .....

----

[22:11:56 INFO]: [BKCommonLib] Loading BKCommonLib v1.16.3-v1                                                 
> WARNING: An illegal reflective access operation has occurred                                                
WARNING: Illegal reflective access by com.bergerkiller.mountiplex.reflection.util.GeneratorClassLoader (file:/root/paper-mc/plugins/BKCommonLib-1.16.3-v1.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,
byte[],int,int)                                                                                               
WARNING: Please consider reporting this to the maintainers of com.bergerkiller.mountiplex.reflection.util.GeneratorClassLoader
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations                                                                                                                       
WARNING: All illegal access operations will be denied in a future release  

----

note even tho it is reporting BKCommonLib of v1, the only version in the server plugins folder is the v2-SNAPSHOT

#### Expected behaviour:

the warning message not to show.

#### Steps to reproduce:

running a paper mc server with BKCommonLib installed in the plugins folder.

**Comment by weeryan17** [comment]
This is due to newer java versions, not actually an issue with the plugin. This error can be safely ignored.
