### ISSUE TITLE
How to find a tuto for sending an image on a map for a specific player ?

### ISSUE THREAD

**Issue by Anarchick** [bergerhealer/BKCommonLib#109]
Hi, I can't find any link to a Discord for this plugin or a link of a Wiki for my goal : "How to send an image (BufferedImage) Map to a specific player".

I'm new in java dev, I had try to manually do this, but I think using your API is better.

I'm creating an Addon for Skript and I would like to create this Method : 
```java
	static public void sendMap(int id, BufferedImage image, Player[] players) {
		MapTexture texture = MapTexture.fromImage(image);
		// MapDisplay ?
		for (Player player : players) {
			// ???? Things about owners of MapDisplay I guess
		}```

For my v1, I will use specific Map ID , and for v2 a screen of X by X item frames.

Can anyone help me ? (Or send me a link to a discord support ? I'm not fan of using Github for things as help ^^). Thanks.

**Comment by bergerkiller** [comment]
Link to discord is here: https://discord.gg/q9gutsN

Firstly, the map display API in BKCommonLib doesnt operate on map ids, not does it send map updates externally. You create a custom class, like this one, that extends MapDisplay:

https://github.com/bergerhealer/BKCommonLib/blob/master/src/main/java/com/bergerkiller/bukkit/common/map/test/MapTestDisplay.java

Then you create a map item using MapDisplay.createMapItem(MyClass.class), and give that to the player. All the synchronization to the player is done by bkcommonlib, you don't work with map id's at all.

If you want each player to see a unique different image, you need to call setGlobal(false) in onAttached():

https://github.com/bergerhealer/BKCommonLib/blob/master/src/main/java/com/bergerkiller/bukkit/common/map/MapDisplay.java#L266
