### ISSUE TITLE
CommonTabController messing maxPlayer count

### ISSUE THREAD

**Issue by YellowZaki** [bergerhealer/BKCommonLib#110]
##### Spigot version: Tuinity Paper Fork 1.16.3

<hr>

#### Problem or bug:

I was having problems about players not being able to join the server because it was full.
Then I realised the max player count (which is set to 90) was changing mid-game to 60 sometimes. Then return back to 90.

I started viewing plugins resource code one by one looking for code that change the max player count until I found this.
https://github.com/bergerhealer/BKCommonLib/blob/dc234eb9bed43d6ede9ba4f09f4b4f3bbc24e0fc/src/main/java/com/bergerkiller/bukkit/common/internal/CommonTabController.java#L260
https://github.com/bergerhealer/BKCommonLib/blob/dc234eb9bed43d6ede9ba4f09f4b4f3bbc24e0fc/src/main/java/com/bergerkiller/bukkit/common/internal/CommonTabController.java#L269
#### Expected behaviour:
Fix the error or being able to disable the TabController via config (I'm not using it, I just use BKCommonLib for LightCleaner).

#### Steps to reproduce:

Here is a log info: https://pastebin.com/4xwGarj8

1. Players join fine until there are 63 players. 
2. MaxPlayers set to 60
3. Then a player is kicked because 60 max players.
4. MaxPlayers set to 90
5. Then players joining fine until there are 70 players.
6. MaxPlayers set to 60
7. Players decreasing (because they can't join) until there are 63 players
8. MaxPlayers set to 90

**Comment by bergerkiller** [comment]
What plugin is still using that tab controller API though? That stuff has been broken for a while. Or does it also mess with max player count when no other plugin is usingit?

**Comment by YellowZaki** [comment]
I don't know, I installed BKCommonLib because of LightCleaner.
I guess no other plugin is using it.

**Comment by bergerkiller** [comment]
Well without that, BKCommonLib doesnt change max player count at all.

Unless another plugin is using that tab controller api thingy, then everything stays at initialization:
`customListCount = serverListCount = 0;`

```
    private boolean hasChangedMaxPlayers() {
        return customListCount > serverListCount;
    }
```

```
            // Temporarily set the max player count to the one as specified here
            if (hasChangedMaxPlayers()) {
                CommonNMS.getPlayerList().setMaxPlayers(customListCount);
            }
```

So I doubt in this instance BKC is to blame here. Can you check whether the issue goes away when bkc is uninstalled?

**Comment by YellowZaki** [comment]
I've removed bkc, let's see if it happens.

It is really strange. I batch decompiled all the plugins and then I searched for "setMaxPlayers" and similar methods. And I only found bkc.

**Comment by bergerkiller** [comment]
Search for "maxPlayers" too, as that is the name of the field in PlayerList.java

**Comment by YellowZaki** [comment]
I haven't found anymore plugins. Just BKCommonLib.

I'm seeing that CommonPlugin has an instance of CommonTabController, that uses controller.setDefaultSize() on enable, which changes some variables from CommonTabController.
Also TabUpdater is scheduled and it interacts with the tabcontroller...

I don't know how it works, but there are things that doesn't stay at initialization.

For now, without BKC there hasn't been any problems with player limits. I'll keep testing.

Maybe a debug message when setMaxPlayers() is going to be executed by BKCommonLib would be useful. Something like: [Debug] MaxPlayers is going to set to x

**Comment by bergerkiller** [comment]
> For now, without BKC there hasn't been any problems with player limits.

I'll do some testing then, thanks. It's been years ago that any of this was written, so who knows, maybe there's a bug in it that only now is being found

**Comment by bergerkiller** [comment]
Looks like you're right. It's initializing some default tab size, and as a result even if no plugin is using it, it demands a minimum tab list player count of 20. I think I'll throw this default behavior out, since it was only meant for if plugins used the tab control api wrong and created a tab view after the server was started.

**Comment by bergerkiller** [comment]
Considered trying to fix it, but it looks like it is doing several things wrong. Among which, assuming the configured max player count of the server never changes. Decided to wipe the api from BKCommonLib entirely, as it hasn't been tested for years.

You can check if the issue goes away

https://ci.mg-dev.eu/job/BKCommonLib/931/

**Comment by YellowZaki** [comment]
Ok thank you, I've installed the plugin again. I'll let you know if there are problems.
