### ISSUE TITLE
illegal reflective access

### ISSUE THREAD

**Issue by seema84** [bergerhealer/BKCommonLib#115]
##### BkCommonLib version:
BKCommonLib v1.16.5-v2

##### Paper version:
Paper version git-Paper-457 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

<hr>

#### Problem or bug:

[BKCommonLib] Loading BKCommonLib v1.16.5-v2
>....WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.bergerkiller.mountiplex.reflection.util.GeneratorClassLoader (file:/mnt/minecraftbukkit/plugins/BKCommonLib-1.16.5-v2.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
WARNING: Please consider reporting this to the maintainers of com.bergerkiller.mountiplex.reflection.util.GeneratorClassLoader
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by Andre601** [comment]
Not an issue. Ignore it

**Comment by bergerkiller** [comment]
Yeah this is normal, and can be ignored. It's because Im using reflection to call a JVM method, which java doesnt like for security reasons. But (for now) its just a warning and works fine for the foreseeable future.

**Comment by seema84** [comment]
all right i just wanted to mention it

**Comment by Andre601** [comment]
You're not the first and for sure won't be the last one reporting this.

**Comment by bergerkiller** [comment]
Found some ways to quench the warnings, but not sure if all code paths are covered. No longer does it at startup at least.

https://github.com/bergerhealer/BKCommonLib/commit/5d91ce29875ab99aae3244e92437b724eba99261

**Comment by bergerkiller** [comment]
This problem should be fixed, hopefully. Let me know if there are any other moments where this warning pops up. https://github.com/bergerhealer/Mountiplex/commit/d05c9fb4983618154b323534440cb4430f79ccc2

https://ci.mg-dev.eu/job/BKCommonLib/1037/

**Comment by seema84** [comment]
at the moment (build 1037) i see this

[Server thread/WARN]: [REFLECTION] Method modifiers of protected void trackEntity:addEntity((org.bukkit.entity.Entity) Entity entity); do not match (public expected)
[Server thread/WARN]: [REFLECTION] Method modifiers of protected void setRotation:setYawPitch(float yaw, float pitch); do not match (public expected)
[Server thread/WARN]: [REFLECTION] Method modifiers of protected void trackEntity:addEntity((org.bukkit.entity.Entity) Entity entity); do not match (public expected)

**Comment by bergerkiller** [comment]
Ill fix those too, but luckily they don't cause any problems.

**Comment by bergerkiller** [comment]
Closing this issue ticket now, as it's been fixed. The modifier warnings should be fixed too, but can be tracked here. https://github.com/bergerhealer/BKCommonLib/issues/120
