### ISSUE TITLE
Incompatibility between BKCL 1010/1011 and TC

### ISSUE THREAD

**Issue by LaurenceBarnes** [bergerhealer/BKCommonLib#117]
## Info
Please provide the following information:

**I used the template from TrainCarts because I first typed it there. It is actually a BKCommonLib issue.**

- BkCommonLib Version (`/train version`): 1011/1010
- TrainCarts Version (`/train version`): 865/864
- Server Type and Version (`/version`): Tuinity-190

----
### Description
The 1010 patch of BKCommonLib, apparently that mountiplex update, broke compatibility with TrainCarts, and of course TCCoasters with that too (since it depends on TC). The other plugins I use work (I don't use SignLink, idk about that). I tested with Both TC-864/865 and removed TCCoasters (added it in after I noticed that BKCL-1009 works).

The error during startup:
1011: https://pastebin.com/BFXGMuf5
1010: https://pastebin.com/Ugi9a6c7

One time this happened (1011)
Interesting because a different error, and a lot of spam after the startup was completed (plus additional error during the late startup phase)

https://pastebin.com/JXHcL7aZ

### Expected behaviour
What do you expect TrainCarts to do?
I expect it to work xD

### Actual behaviour
What is TrainCarts doing instead?
It does not work :(

### Steps to reproduce
Use this BKCL build and TrainCarts build together

### Additional Information
Any additional information we should know of?
I love your plugins <3

**Comment by djbenbe** [comment]
use the stable version 1008.
this one works fine without errors

**Comment by LaurenceBarnes** [comment]
I know, I am using 1009, which I mentioned in that issue. That is also stable.
Thanks anyway!

**Comment by bergerkiller** [comment]
Yeah I'm working on this issue, it's a little complex as it involves a bug deep inside javassist itself. But I'll figure it out :)

**Comment by bergerkiller** [comment]
Should hopefully be fixed now https://ci.mg-dev.eu/job/BKCommonLib/1012/

**Comment by LaurenceBarnes** [comment]
seems to be working, it doesn't complain anymore :D
