### ISSUE TITLE
REFLECTION warnings.

### ISSUE THREAD

**Issue by mibby** [bergerhealer/BKCommonLib#118]
BKCommonLib 1.16.5 v3 dev 1012
Paper dev 487

Paper recently implemented Adventure and some other changes. BKCommonLib's REFLECTION check now seems to output two warnings.

```
[03:38:31] [Server thread/INFO]: [BKCommonLib] Loading BKCommonLib v1.16.5-v3-SNAPSHOT
[03:38:34] [Server thread/WARN]: [REFLECTION] Field 'private int c' in class net.minecraft.server.v1_16_R3.PacketPlayOutTitle skipped 1 fields during lookup:
[03:38:34] [Server thread/WARN]: [REFLECTION]   - public net.kyori.adventure.text.Component adventure$text;
```

**Comment by bergerkiller** [comment]
Fairly harmless, since I dont use that particular packet anyway and that warning (at least this time) doesn't point out a real issue. I'll try to fix that though

**Comment by Andre601** [comment]
PaperMC now uses kyori adventure instead of the bungeecord api. So maybe it comes from that?
Although the old methods still exist but is deprecated.

**Comment by bergerkiller** [comment]
They just added a field, and mountiplex/bkcommonlib warns when a field exists that it didnt expect according to the template. All I got to do is add an 'unknown' field reference to it. But if that value is based on some other field then I should write the appropriate getters and setters.

But again, I dont use the packet, so its not really that urgent

**Comment by mibby** [comment]
It does seem to delay server start-up by a few seconds when it checks for what it's worth.

**Comment by bergerkiller** [comment]
That should do it: https://ci.mg-dev.eu/job/BKCommonLib/1013/

**Comment by seema84** [comment]
can confirm this issue with build 1033

**Comment by bergerkiller** [comment]
Anyone still has reflection warnings like this? Have not seen them testing all versions 1.8 - 1.18

**Comment by seema84** [comment]
currently in v1.17.1-v5 I have not seen any more

**Comment by bergerkiller** [comment]
Alrighty, think I can close it then
