### ISSUE TITLE
Error valid Packet Handler

### ISSUE THREAD

**Issue by TheCalypso** [bergerhealer/BKCommonLib#125]
##### Spigot version:
Paper 1.16.5 - 778 

<hr>

#### Problem or bug:
![image](https://user-images.githubusercontent.com/33781244/122641774-93d33200-d107-11eb-812f-a486bfbf8bc5.png)

#### Expected behaviour:
I run with Java 16

**Comment by bergerkiller** [comment]
A workaround would be installing protocollib, though I dont know why that particular class doesnt exist on your server

**Comment by TheCalypso** [comment]
Hello, thank you for your quick response! Indeed I was using the last version of Protocolibs compatible with Minecraft 1.17. However, this version of Protocolibs doesn't like Minecraft 1.16 ^^
So I put a slightly older version of Protocolibs!

Thank you very much and good luck !
