### ISSUE TITLE
BKCommonLib Maven Repo?

### ISSUE THREAD

**Issue by Dymeth** [bergerhealer/BKCommonLib#126]
Looks like https://ci.dj-tcraft.nl/plugin/repository/everything/ doesn't work. Specified at: https://dev.bukkit.org/projects/bkcommonlib#title-4-1

Is there any up-to-date repository?

**Comment by bergerkiller** [comment]
As seen in the pom.xml of the projects, its at https://ci.mg-dev.eu/plugin/repository/everything/

**Comment by Dymeth** [comment]
It works, thank you!
