### ISSUE TITLE
1.16.5 - BKCommonLib not initializing when using MohistMC

### ISSUE THREAD

**Issue by Simonluethi** [bergerhealer/BKCommonLib#129]
##### BkCommonLib version:
v1.16.5-v3 and above

##### MohistMC version:
1.16.5 - #701 and newer

<hr>

#### Problem or bug:
BKCommonLib does not initialize when starting the MohistMC Server. Causing issues, like the other plugins not loading in due to requiring BKCommonLib.

#### Expected behaviour:
BKCommonLib to inizialize so that the other Plugins requiring it work. Like Traincarts for example.

#### Steps to reproduce:
1. Putting the Plugin into the Plugins Folder
2. Starting the Server

#### Error Log
https://pastebin.com/diikTY7b

#### Note
1. I am unsure if it is the Plugin or MohistMC itself. But i thought posting the issue here is a good idea.
2. I tried also adding in the 1.17 version, still doesnt work and the same errors pop up.

**Comment by BoenShi128** [comment]
I met this problem too.I don't know whether it is the mohist's problem or not.But I can't use this plugin.I hope this bug will be fixed that I can use Mohist with this plugin and traincraft.Thanks!

**Comment by bbayu123** [comment]
Closing issue, BKCommonLib already works with Spigot and Paper. If Mohist doesn't work, that's something Mohist needs to fix.
