### ISSUE TITLE
PacketPlayOutEntityTeleport:

### ISSUE THREAD

**Issue by Mr-toaster111** [bergerhealer/BKCommonLib#14]
##### Spigot version:

<hr>

#### Problem or bug:
http://pastebin.com/8VRrST3z
#### Expected behaviour:
cannot get the location packet
#### Steps to reproduce:
fix the fields

**Comment by mg-1999** [comment]
Gonna look into this when I have some free time.

**Comment by Mr-toaster111** [comment]
Alright sweet, when are you planning on starting the traincarts updates? Obviously there's still some bugs to fix in BK but i can give you a hand if you want

**Comment by mg-1999** [comment]
Fixing all the packets in a moment. Then gonna look into TC.

**Comment by mg-1999** [comment]
@Mr-toaster111 There is a class called `PacketTypeClasses` in `com.bergerkiller.bukkit.common.protocol`. You just need to check if the packet fields have changed and if so retrieve appropriate names from the MCP Project I've done some of it, but it costs more time then I remember. I will push it to the dev branch.

**Comment by FriwiDev** [comment]
I already updated a bunch but as it didnt fire errors on startup i considered all fields as ok. Sorry if that wasnt correct.

**Comment by mg-1999** [comment]
I made TC compatible with 1.9 but that gives even more errors, haven't push
it yet.

Op ma 14 mrt. 2016 om 22:59 schreef Friwi <notifications@github.com>:

> I already updated a bunch but as it didnt fire errors on startup i
> considered all fields as ok. Sorry if that wasnt correct.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bergerhealer/BKCommonLib/issues/14#issuecomment-196539648>
> .
>
-- 

Met vriendelijk groeten,

Matthijs Giezenberg

**Comment by Mr-toaster111** [comment]
Any updates?

**Comment by mg-1999** [comment]
It is more work then I thought it would be. Because I work fulltime and also have a social life, I can't dedicate the time I would like to dedicated to this project. I will be finishing it and I won't abandon it. Just give it a few more days and it wil be _ready_.

**Comment by Mr-toaster111** [comment]
Yeah that's fine take your time
