### ISSUE TITLE
High amount of ticks - timings

### ISSUE THREAD

**Issue by lostINParadies** [bergerhealer/BKCommonLib#141]
##### Spigot version: 
This server is running Paper version git-Paper-274 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 04c7b16)
You are 9 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-268 (MC: 1.18.2)

<hr>

#### Problem or bug: high amount of ticks in timings. Is this a problem?

https://ibb.co/NSjDhqm
https://ibb.co/HVbW6RF

**Comment by VoChiDanh** [comment]
i have same problem but paper 1.17.1 with latest release from spigotmc

**Comment by bergerkiller** [comment]
Can you run spark instead? That helps me a lot more. It does seem high

**Comment by VoChiDanh** [comment]
> Can you run spark instead? That helps me a lot more. It does seem high. If youre using the LAG tab though, thats highly misleading for frequently run tasks, because it sorts very minor things all the way at the top when nothing meaningful is happening on the server otherwise.

https://spark.lucko.me/RivwiQTlqx

**Comment by bergerkiller** [comment]
![ScreenShot 2022-09-04 14 15 16](https://user-images.githubusercontent.com/957601/188312913-adf5f93f-18ac-4ce4-80e8-2ebef62e7353.jpg)
Like I thought, its measuring the margins here. The server is sleeping 97% of the tick.

Like I said, if nothing is happening on the server, even the tiniest things that do happen show up a scaring red. That's a major problem of timings showing the LAG tab by default.

**Comment by VoChiDanh** [comment]
> ![ScreenShot 2022-09-04 14 15 16](https://user-images.githubusercontent.com/957601/188312913-adf5f93f-18ac-4ce4-80e8-2ebef62e7353.jpg) Like I thought, its measuring the margins here. The server is sleeping 93% of the tick.
> 
> Like I said, if nothing is happening on the server, even the tiniest things that do happen show up a scaring red. That's a major problem of timings showing the LAG tab by default.

So does it affect the server?

**Comment by bergerkiller** [comment]
No.

**Comment by bergerkiller** [comment]
Also why are none of you sending the original timings link? Its made worse by cutting off what tab youre viewing.

**Comment by VoChiDanh** [comment]
> Also why are none of you sending the original timings link? Its made worse by cutting off what tab youre viewing.

Do you mean this https://timings.aikar.co/dev/?id=f785694f82704aa585c24d7525c151b7#timings ?

**Comment by bergerkiller** [comment]
> > Also why are none of you sending the original timings link? Its made worse by cutting off what tab youre viewing.
> 
> Do you mean this https://timings.aikar.co/dev/?id=f785694f82704aa585c24d7525c151b7#timings ?

Yup! Much more useful. I can now see that there were 8 ticks with >200ms processing, which is odd. But the lag tab is extremely confusing to read as it is. There's no structural problem by the look of things.

If you do want to diagnose those potential lag spikes, run this spark command which only measures >50ms ticks.
`/spark profiler --only-ticks-over 50`

Make sure to run it for at least 20 minutes.

**Comment by VoChiDanh** [comment]
> > > Also why are none of you sending the original timings link? Its made worse by cutting off what tab youre viewing.
> > 
> > 
> > Do you mean this https://timings.aikar.co/dev/?id=f785694f82704aa585c24d7525c151b7#timings ?
> 
> Yup! Much more useful. I can now see that there were 8 ticks with >200ms processing, which is odd. But the lag tab is extremely confusing to read as it is. There's no structural problem by the look of things.
> 
> If you do want to diagnose those potential lag spikes, run this spark command which only measures >50ms ticks. `/spark profiler --only-ticks-over 50`
> 
> Make sure to run it for at least 20 minutes.

https://spark.lucko.me/4y1nMljNFr

**Comment by VoChiDanh** [comment]
https://timings.aikar.co/dev/?id=937cb89050fd47dd9a4d35157760b3c8

ah ye, it stopped being red and now it's red elsewhere and I don't know what's causing it, thanks

**Comment by bergerkiller** [comment]
I don't think you have a problem at all. Your MSPT is a solid 20, isnt it? If there is no problem why are you worried about red numbers in timings, especially if thats under the **lag** tab which shows only exceptional cases?

**Comment by bergerkiller** [comment]
I've just been informed that the >= 50 is probably not correct, as spark makes no difference between sleeping and processing.

IF there are lag spikes, they should show up when you run
`profiler --only-ticks-over 100`

(So over 100ms long)

**Comment by VoChiDanh** [comment]
https://timings.aikar.co/dev/?id=bd299e60b3474fb190239601afea6c6b ^

**Comment by bergerkiller** [comment]
You have no problem whatsoever. Server tick is like 3ms per tick. There's nothing to measure at this level. Spark shows nothing wrong, except for some outliers when a background save occurs or some classes are loaded in some plugin. Nothing scary about that.

You don't have a problem on your server @VoChiDanh but @lostINParadies 's situation might be different.

**Comment by bbayu123** [comment]
Closing issue, not an issue to begin with, just a small misunderstanding.
