### ISSUE TITLE
Index out of bounds

### ISSUE THREAD

**Issue by Stogalosu** [bergerhealer/BKCommonLib#142]
##### Spigot version: 1.18.1-R0.1

<hr>

#### Problem or bug: When creating a new method in a class that extends MapWidgetTabView and calling setSelectedIndex() inside of it, I receive error Index out of bounds, but when calling it inside an already defined method like onAttached() or onRightClick(), it works just fine
[Code.txt](https://github.com/bergerhealer/BKCommonLib/files/8548104/Code.txt)
[Error.txt](https://github.com/bergerhealer/BKCommonLib/files/8548110/Error.txt)

**Comment by bergerkiller** [comment]
Youre trying to use bukkit event handlers inside a map widget, something that isn't really supported. Are you sure the event is fired for a valid widget instance, and not one that has been detached / removed? Check by comparing

System.out.println(System.identityHashCode(this));

in onAttached vs your event handler.

Your error points towards an onTick but your code sample has none.

**Comment by bergerkiller** [comment]
If events are firing for a detached/invalid listener, then most likely getTabCount() is 0, explaining the error.

And if you really want a listener in there, register it in onAttached() and use this method to unregister the listener in onDetached():

https://github.com/bergerhealer/BKCommonLib/blob/master/src/main/java/com/bergerkiller/bukkit/common/utils/CommonUtil.java#L1012

**Comment by bbayu123** [comment]
Closing issue, invalid issue - not a BKCommonLib problem in the first place.
