### ISSUE TITLE
Error Console

### ISSUE THREAD

**Issue by Hazugg** [bergerhealer/BKCommonLib#144]
##### Spigot version: 1.18.2

<hr>

#### Problem or bug: 
I always get this error when starting the server

![image](https://user-images.githubusercontent.com/31551514/170901547-31a5b2ba-9b5e-49d3-b41c-df1232fdd194.png)

**Comment by bbayu123** [comment]
Not a bug, this is correct behaviour. This is needed to maintain backwards compatibility with 1.8 - 1.12.

**Comment by Hazugg** [comment]
List thanks, I thought it could give a problem in the future
