### ISSUE TITLE
Error messages with MyWorlds on Paper

### ISSUE THREAD

**Issue by owu-1** [bergerhealer/BKCommonLib#147]
##### Spigot version: paper-1.19.2-174

<hr>

#### Problem or bug:
Error messages pop up when using MyWorlds with BKCommonLib. Nothing else seems odd, though I've only tried breaking a block.
The errors don't show up on paper-1.19.2-173. It should be something to do with the rewrite of the chunk system here https://github.com/PaperMC/Paper/commit/01a13871deefa50e186a10b63f71c5e0459e7d30
[latest.log](https://github.com/bergerhealer/BKCommonLib/files/9645046/latest.log)
#### Expected behaviour:
Error messages not to pop up
#### Steps to reproduce:
Use the versions of BKCommonLib and paper with MyWorlds-1.19.2-v1-SNAPSHOT-171

**Comment by bergerkiller** [comment]
Probably related to papers new chunk system? Will take a moment for me to patch for that.

**Comment by bergerkiller** [comment]
Try with https://ci.mg-dev.eu/job/BKCommonLib/1386/

**Comment by owu-1** [comment]
The new build doesn't have any error messages. Thanks bergerkiller!
