### ISSUE TITLE
Occasional group of errors with MyWorlds on Paper

### ISSUE THREAD

**Issue by owu-1** [bergerhealer/BKCommonLib#148]
##### Spigot version: paper-1.19.2-175

<hr>

#### Problem or bug:

A group of error messages pop up occasionally when using MyWorlds with BKCommonLib. I've only had it happen two times with 5 hours between. The server last started 27/09/22 08:01 and these error messages popped up at 29/09/22 08:31.

Looks very similar to https://github.com/PaperMC/Paper/issues/8396, except I have an extra line in the stack trace
```at com.bergerkiller.bukkit.common.internal.logic.EntityAddRemoveHandler_1_19_2_Paper_ChunkSystem$Hook.c(Unknown Source) ~[?:?]```
[partial-log.txt](https://github.com/bergerhealer/BKCommonLib/files/9670889/partial-log.txt)

#### Expected behaviour:

The error messages to not show up

#### Steps to reproduce:

Plugins: MyWorlds-1.19.2-v1-SNAPSHOT-171, coreprotect, discordsrv, luckperms, spark, squaremap
Run the server with players on for a while

**Comment by bergerkiller** [comment]
See: https://github.com/PaperMC/Paper/issues/8396

Not related to bkcommonlib
