### ISSUE TITLE
Plugin crashes on startup because of [BKCommonLib.Conversion] Failed to initialize getEntityPlayer()

### ISSUE THREAD

**Issue by Kshtij-7** [bergerhealer/BKCommonLib#168]
##### Spigot version: 1.20.1 (paper)

<hr>

**Comment by bergerkiller** [comment]
can you try with 1.20.6-v1? TC and TCC and myworlds also need to be updated.

https://ci.mg-dev.eu/job/BKCommonLib/1743/
https://ci.mg-dev.eu/job/TrainCarts/1571/
https://ci.mg-dev.eu/job/TC%20Coasters/343/

**Comment by Kshtij-7** [comment]
Working now. Thanks!!
