### ISSUE TITLE
net.minecraft.server.EntityTrackerEntry 'w' has changed from Entity to List<Entity> in 1.9

### ISSUE THREAD

**Issue by kpaulisse** [bergerhealer/BKCommonLib#20]
##### Spigot version: lib/spigot-1.9 of this repo

<hr>

#### Problem or bug

TrainCarts exposes a change to net.minecraft.server been updated in BKCommonLib. This causes https://github.com/bergerhealer/TrainCarts/issues/62. I tracked this down to the following underlying change in net.minecraft.server.EntityTrackerEntry:

1.8:
```
public class EntityTrackerEntry {
...
    private Entity w;
...
}
```

1.9:
```
public class EntityTrackerEntry {
...
    private List<Entity> w = Collections.emptyList();
...
}
```

I'm guessing https://github.com/bergerhealer/BKCommonLib/blob/master/src/main/java/com/bergerkiller/bukkit/common/reflection/classes/EntityTrackerEntryRef.java#L17 and/or https://github.com/bergerhealer/BKCommonLib/blob/master/src/main/java/com/bergerkiller/bukkit/common/conversion/type/HandleConverter.java#L37-L54 needs an update.

#### Expected behaviour:

Don't get error messages described in https://github.com/bergerhealer/TrainCarts/issues/62

#### Steps to reproduce:

Start spigot with current master checkout of BKCommonLib and TrainCarts.

**Comment by mg-1999** [comment]
Already fixed on a local version.

**Comment by kpaulisse** [comment]
:cool: Glad to hear you've tracked that down. Would you be willing to push that up to a separate branch so I can grab it? I'd like to try to get TrainCarts going for 1.9. Thanks!

**Comment by mg-1999** [comment]
Pushed it to the develop-1.9 branch.

**Comment by kpaulisse** [comment]
👍 Thanks!
