### ISSUE TITLE
java.lang.RuntimeException: java.lang.IllegalArgumentException: wrong number of arguments

### ISSUE THREAD

**Issue by no-lifer** [bergerhealer/BKCommonLib#24]
##### Spigot version: 1.9.2

<hr>

#### Problem or bug: http://pastebin.com/JSZVZ2jx

How can i fix this? it's dev build 1,9 in combination with last version traincarts.

**Comment by mg-1999** [comment]
Are you using the latest version?

Op do 19 mei 2016 12:49 schreef no-lifer <notifications@github.com>:

> BkCommonLib version: 1.75 Spigot version: 1.9.2
> ------------------------------
> Problem or bug: http://pastebin.com/JSZVZ2jx
>
> How can i fix this? it's dev build 1,9 in combination wit traincarts.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/bergerhealer/BKCommonLib/issues/24>
>
-- 

Met vriendelijk groeten,

Matthijs Giezenberg

**Comment by no-lifer** [comment]
this download and build where like 3 hours ago from bkcommonlib  1,9.

**Comment by FriwiDev** [comment]
So you are using 1.8 traincarts with 1.9 bkcommonlib? good luck

**Comment by mg-1999** [comment]
Fixed in latest release.

Op do 19 mei 2016 15:03 schreef no-lifer <notifications@github.com>:

> this download and build where like 3 hours ago from bkcommonlib 1,9.
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/bergerhealer/BKCommonLib/issues/24#issuecomment-220317593>
>
-- 

Met vriendelijk groeten,

Matthijs Giezenberg

**Comment by no-lifer** [comment]
@FriwiDev nope? is 1.9  traincarts

**Comment by no-lifer** [comment]
I wondering, it looks like i do something wrong but i'm not even logged in :

**Comment by no-lifer** [comment]
I wondering, it looks like i do something wrong but i'm not even logged in and got big error logs; http://pastebin.com/utHxKA2w do i use something wrong from java ? i only build it that's all?

**Comment by mg-1999** [comment]
You are not using the latest bkcommonlib or TrainCarts. Try updating them
from https://ci.mg-dev.eu and use the UNSTABLE versions

Op di 24 mei 2016 00:30 schreef no-lifer <notifications@github.com>:

> I wondering, it looks like i do something wrong but i'm not even logged in
> and got big error logs; http://pastebin.com/utHxKA2w do i use something
> wrong from java ? i only build it that's all?
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/bergerhealer/BKCommonLib/issues/24#issuecomment-221115426>
>
-- 

Met vriendelijk groeten,

Matthijs Giezenberg

**Comment by no-lifer** [comment]
http://pastebin.com/ZEKvdim1 almost there this is the last version. still errors but other errors this time:)

**Comment by mg-1999** [comment]
You Have two bkc versions in your plugin folder.

Op di 24 mei 2016 11:30 schreef no-lifer <notifications@github.com>:

> http://pastebin.com/ZEKvdim1 almost there this is the last version. still
> errors but other errors this time:)
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/bergerhealer/BKCommonLib/issues/24#issuecomment-221215570>
>
-- 

Met vriendelijk groeten,

Matthijs Giezenberg

**Comment by no-lifer** [comment]
Sorry, did see that still http://pastebin.com/pf1s6bCP

**Comment by nolifer123** [comment]
Hi , what is the bug do i run the wrong Java or ???
http://pastebin.com/pf1s6bCP

**Comment by mg-1999** [comment]
No it is a bug in bkc, thanks for the report.

Op zo 29 mei 2016 10:55 schreef nolifer123 <notifications@github.com>:

> Hi , what is the bug do i run the wrong Java or ???
> http://pastebin.com/pf1s6bCP
>
> —
> You are receiving this because you were mentioned.
>
> Reply to this email directly, view it on GitHub
> <https://github.com/bergerhealer/BKCommonLib/issues/24#issuecomment-222349971>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AGmkdj3rSHFcA1WpahKsAniIA3fxEtL6ks5qGVSOgaJpZM4IiIzh>
> .
>
-- 

Met vriendelijk groeten,

Matthijs Giezenberg

**Comment by nolifer123** [comment]
Okay any idea about ETA?

**Comment by FriwiDev** [comment]
I already provided a fix for this issue and updated a major part of TrainCarts a while ago. Sadly my changes are not in the main build tree.

**Comment by nolifer123** [comment]
That's really strange.... why wouldn't you update it to the main if the build is good.

I mean this script isn'the working at all at the moment.
Wondering how long the eta for new build will be.

Offcourse I know its a free plugin but it's a really important plugin.
Maybe let people pay for the plug in so you guys get some profit out of it?

**Comment by mg-1999** [comment]
Because the master tree is 1.8 and any development is in the development branch.
