### ISSUE TITLE
Logs spammed - [BKCommonLib] TileEntity is in Entity List!

### ISSUE THREAD

**Issue by kpaulisse** [bergerhealer/BKCommonLib#3]
```
[21:05:25 WARN]: [BKCommonLib] TileEntity is in Entity List!
[21:05:25 WARN]: [BKCommonLib] TileEntity is in Entity List!
[21:05:25 WARN]: [BKCommonLib] TileEntity is in Entity List!
```

Comes from com.bergerkiller.bukkit.common.entity.CommonEntity and watching this through a debugger looks like there are hundreds of objects in the list that meet the "obj instanceof TileEntity" condition. An easy fix would be to comment out the log line and let the server continue. However I don't know enough about this to know whether we need to be concerned about this message -- i.e. did something change in 1.8 or is something wrong with my world.

**Comment by FriwiDev** [comment]
Yeah. This was just a workaround to keep the plugin on loading. I will fix this soon (hopefully).

**Comment by Bart-0110** [comment]
Why not just remove these lines
https://github.com/bergerhealer/BKCommonLib/blob/master/src/main/java/com/bergerkiller/bukkit/common/entity/CommonEntity.java#L335-L336

**Comment by DJmaxZPL4Y** [comment]
I think you must create an boolean in the config for turning off the warns so you can work and it isn't spamming the logs for the server who must use the plugin

**Comment by mg-1999** [comment]
It is already removed and it was just a debug message for us.
