### ISSUE TITLE
Player Skulls "Vanishing"

### ISSUE THREAD

**Issue by HyperionNexus** [bergerhealer/BKCommonLib#30]
BkCommonLib version: 1.70-2
Spigot version: Build 42 for 1.8.8

Problem or bug: When placing any custom head other than the vanilla ones, the skin will display until you log out or unload the chunks. This is some kind of compatibility issue with ProtocolLib, as it fixes itself if one or the other is removed.

Expected behavior: For the player heads to not lose their skin.

Steps to reproduce: Logging out of server or unloading the chunks causing it to return to the Steve head.

I also posted it on [ProtocolLib's issue tracker](https://github.com/dmulloy2/ProtocolLib/issues/293).

**Comment by bergerkiller** [comment]
this issue is very old and Ive failed to reproduce it myself. Fixed? I can always re-open if its not.
