### ISSUE TITLE
Citizens not working properly

### ISSUE THREAD

**Issue by DynamicThijs** [bergerhealer/BKCommonLib#31]
##### Spigot version: 1.11.2 latest build

<hr>

#### Problem or bug:
When using BKCommonLib and Citizens together, all non-player NPCs are hidden (they do make sounds), the Citizens config doesn't save anymore and Citizens logs this error to the console: 

[Citizens] Could not fetch entity id mapping fields: Can not set static final net.minecraft.server.v1_11_R1.RegistryMaterials field net.minecraft.server.v1_11_R1.EntityTypes.b to net.citizensnpcs.nms.v1_11_R1.util.CustomEntityRegistry.

#### Expected behaviour:
No error, visible NPCs and a working Citizens saves.yml
#### Steps to reproduce:
Install Citizens and BKCommonLib, type /npc create test --type horse (for example) and it's invisible. Then remove the npc and type /citizens save and /citizens reload. The NPC is back again, but it should be gone.

When removing BKCommonLib, all issues with Citizens are gone.

**Comment by bergerkiller** [comment]
Should be fixed again now (not in release, but current build tree) now that I made changes to prevent citizens from thinking BKCommonLib modifies the entity type registry. It should be fine now.
