### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mat41997** [bergerhealer/BKCommonLib#34]
logs
https://gist.github.com/mat41997/da53ecd5a5616353e1207d893792695b

timings
https://timings.aikar.co/?id=c263b123ac8e4d2183182d1b54a647cc#plugins

torch
https://github.com/TorchSpigot/Torch

**Comment by bergerkiller** [comment]
TorchSpigot...well thats a new one. I have not tested any support for it, and judging just by how many errors exist involving missing fields, I doubt support is even possible. I'll leave it open for future reference

**Comment by bergerkiller** [comment]
Having taken another look, I think support may be possible. Just have to deal with some field renames and method modifier changes.

**Comment by nikehin** [comment]
Close
https://github.com/TorchSpigot/Torch/commit/ec06787571c9526e9f1739129fbf05a78bbe4a06

**Comment by bergerkiller** [comment]
Oh. Well that works too, I suppose. Though if you do wish to change something in Torch and need BKCommonLib support, feel free to re-open this ticket.
