### ISSUE TITLE
Spigot server jars and code is exposed

### ISSUE THREAD

**Issue by bergerkiller** [bergerhealer/BKCommonLib#40]
When depending on BKCommonLib the internal classes (net/minecraft/server, etc) are all exposed as part of the API. This, even though they aren't available on the repository. Only Spigot-API should be exposed, with the implementation code only used under test.

There is also that problem of the jars sitting in the /lib directory, but there isn't much that can be done about that at this time...

**Comment by bergerkiller** [comment]
Big changes have been made with this commit:
https://github.com/bergerhealer/BKCommonLib/commit/ad2f997948c155f90b7a1fb3c3036ee8ef649926

Eventually we will want to remove the Spigot jars from this repository entirely to comply with copyright licensing. That can be done right now by using an off-site repository; but we need to set up the build server to use it + include instructions how to do that.

**Comment by IsaiahPatton** [comment]
What is even the need to have the spigot jars in the repository. Just use Spigot's Maven repo instead of the local one.

**Comment by bergerkiller** [comment]
Forgot to close this. I have removed all spigot jars. It currently resolves the spigot server jars from the protocollib repository. If that breaks some time in the future, build tools should be run before building the project.
