### ISSUE TITLE
[Question] Does MapDisplay API support owner-less Item Frame maps?

### ISSUE THREAD

**Issue by Enveed** [bergerhealer/BKCommonLib#42]
Hello,

first of all, thankyou for your work! Without BKCommonLib and TrainCarts my server wouldnt be what it is today! :)

However, I have a question about the BKCommonLib MapDisplay API I am currently trying to work a bit with.

Is there a way to use this API to display information on maps in Item frames, which are public and do not have an owner, and if so, how?

As far as I understand the map update packets are only sent to owners of the MapDisplay, so is there a way to set it to update the virtual map for everyone in the viewing range of the item frame a map may be in?

Thankyou in advance!

_PS: Your email seems to be dead, or I would've used it for this question_

**Comment by bergerkiller** [comment]
Issue tickets are fine for it :)

I am refining the process. The idea is that map displays have an 'owner', but they don't have to. You can set the session mode of the map display in onAttached so it is kept around when no players are viewing it (FOREVER).

[public void setSessionMode(MapSessionMode mode)](https://github.com/bergerhealer/BKCommonLib/blob/master/src/main/java/com/bergerkiller/bukkit/common/map/MapDisplay.java#L119)

The original idea was to handle the MapShowEvent and add the map display in there. This was convoluted so I have added a mechanism where the map display is stored in the NBT of the item, automatically initialized by BKCommonLib when it is first shown. You can create this item using a simple function and give it to players, or put it in item frames yourselves.

[public static ItemStack createMapItem(Class<? extends MapDisplay> mapDisplayClass)](https://github.com/bergerhealer/BKCommonLib/blob/master/src/main/java/com/bergerkiller/bukkit/common/map/MapDisplay.java#L1028)

Right now, all map displays have the same 'instance'. That is, new players that view the map will see the same thing other players see. If you need different map displays for each player, you can use:

[public void setGlobal(boolean global)](https://github.com/bergerhealer/BKCommonLib/blob/master/src/main/java/com/bergerkiller/bukkit/common/map/MapDisplay.java#L193)

Does this solve your needs, or is there something more needed? I am continuously expanding it, so if theres an edge case not handled right now for sure I'll make sure it is.

**Comment by Enveed** [comment]
Thankyou, this really helped setting up!

It is working great, but sometimes it seems to not call `onTick()` on my `MapDisplay` if I am not holding it. This happened only 2 times now, but it could be possible that it was caused by a server reload. I am currently testing if it occurs too if I use the good old `/stop`.

Also I am currently using `ItemUtil` to save info about the maps state into the NBT data of the item it is attached to, and I also load it the same way. It works great so far, but I just wanted to ask if this is the way it is intended to be done or if there is another way to implement state persistence.

Another thing is, that I am currently trying to find a way to update the `MapDisplay` if the data it is showing changes. I am thinking about registering some kind of update listener to a data provider class in `onAttached()` and remove it in `onDetached()` to avoid unnecessary update calls to unattached `MapDisplay` instances. My question would be now if it is guaranteed that `onDetached()` gets called if there is no attached instance anymore or if `SessionMode.FOREVER` prevents that and I have to find another way to update my `MapDisplays`.

(I don't want to use `onTick()` for update requests as I want drawing and updating logic to be executed separately and the `MapDisplay` only contains the data it is supposed to draw on the next tick)

**Comment by bergerkiller** [comment]
1.) I think onTick is not called when the map isnt being viewed. To call onTick regardless, use setUpdateWithoutViewers(true)

2.) ItemUtil is currently the way to go. I combine it with getMapItem/setMapItem to update state. I plan to eventually include a more generic 'properties' system in the display itself, directly proxying with the map item. But for now, that is all there is. Note that setMapItem can also change the item entirely. For example, set it null to completely remove the map from all places physically.

3.) Tricky question what the best solution is. In one display I've overrided onMapItemChanged and do a re-render there. You can externally, without even knowing the map display, change the item using [this function](https://github.com/bergerhealer/BKCommonLib/blob/master/src/main/java/com/bergerkiller/bukkit/common/map/MapDisplay.java#L1022). It made it easier to handle this sort of refreshing. It will depend on your infrastructure what works best.

What you'd normally do is keep track of a 'dirty' state and re-render the portion that changes. Way down the track I'm considering display elements, or widgets, which behave like this. For example, I can do setValue(12.4) and the fancy widget will automatically re-draw itself to show the new value upon the next tick.

Besides FOREVER you can also use the one above it, HOLDING. So long a player is around with the map item in his inventory, the map display is not removed. Only when nobody is viewing any item frames and nobody has the map in their inventory will onDetached be called.

With FOREVER it is impossible to tell whether there is an offline player with the map item. HOLDING gets closer.

**Comment by Enveed** [comment]
Thanks for the advice, it seems to work just as expected now!

If I get to the point of having another question or problem with the API I'll open another issue!
