### ISSUE TITLE
Horse movement error

### ISSUE THREAD

**Issue by ApocalypsjeNL** [bergerhealer/BKCommonLib#43]
##### Spigot version: git-Spigot-65e8124-357b573 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)

<hr>

#### Problem or bug: 
Horses starts bugging out when teleported and a player is on the horse
https://imgur.com/a/MkHq6

#### Expected behaviour:
The horse should teleport normally even with the player on it

#### Steps to reproduce:
Use this code to spawn a horse and teleport it every tick, Go and sit on the horse and you'll get a bugged horse as shown in the gif

My code:
```
Entity creation:
horse = (Horse) location.getWorld().spawnEntity(location, EntityType.HORSE);
horse.setAdult();
horse.setGravity(false);
horse.setAI(false);

Teleportation:
CommonEntity<?> horseEntity = CommonEntity.get(horse);
horseEntity.setLocation(location.getX(), location.getY(), location.getZ(), rotation, location.getPitch());
```

**Comment by bergerkiller** [comment]
I think that has more to do with the player controlling the horse, while at the same time the horse teleporting. The player controlling horse logic will have to be disabled, somehow. One way would be to handle the vehicle steer packet and cancel it for the horse. I'm not sure if Bukkit has anything...

**Comment by ApocalypsjeNL** [comment]
How could I recreate that with velocity then? I'm not that experienced with entity movement

**Comment by bergerkiller** [comment]
Every tick, take the expected location you want the horse to be at (the location.x/y/z you use now) and subtract from that the horse's current location. This gives you a vector difference. Set the entity velocity to that vector.
