### ISSUE TITLE
BKCommonLib is using 3% of a tick

### ISSUE THREAD

**Issue by Duetro** [bergerhealer/BKCommonLib#54]
##### Spigot version: Spigot 1.12.2-R0.1-SNAPSHOT

<hr>

#### Problem or bug:
BKCommonLib is using ~3% of a tick for a feature which isn't used by us.
Timings report: https://s.duetro.de/i/firefox_2018-11-02_18-46-35.png
Spark profiler: https://s.duetro.de/i/firefox_2018-11-02_18-50-36.png

It would be great if there was a configuration where this could be disabled
#### Expected behaviour:
---
#### Steps to reproduce:
---

**Comment by bergerkiller** [comment]
I assume theres a lot of item frames on the world(s). Do many of them contain a map item inside, or not?

I hate to be adding configuration to BKCommonLib for this, and I suppose just like the resource pack I must make it an item for plugins to tell BKCommonLib a particular map display is in use. It's a little too late for that now, so maybe config is the only option.

Ideally this background task (that basically checks whether the item inside an item frame changes) ONLY fires when the item actually changes. But Bukkit has no API for this, hence it's polling every tick like this. Very wasteful.

Alternative option I see is the (ab)use the player-click-itemframe event to refresh the item then, and do this background polling at a reduced rate. For example, limit the amount of item frames polled every tick to keep those timings below ~0.01%.

**Comment by bergerkiller** [comment]
@Duetro I've made several changes to combat the high tps% usage hotspots as detailed in your profiler report. Some had merit, although counter-intuitive when java is concerned:

- It was checking for itemstack equality in all item frames, even when they do not contain a map item. This strict check was useless, itemstack equality only matters when the item is an actual map anyway
- DataWatcher getRawValue was using reflection to access a private field, often. Hopefully a public method has better performance.
- Every tick it was obtaining the network 'controller' of every item frame holding a map. This created a lot of garbage EntityTracker and EntityTrackerEntry objects, discarded after only a single use.

Commit: https://github.com/bergerhealer/BKCommonLib/commit/a27ec23c248a750dd4bfc6424b8dfe681f711f8b

Let me know how this fares: https://ci.mg-dev.eu/job/BKCommonLib/463/

**Comment by bergerkiller** [comment]
Should be even better now. I've disabled updating of item frames every tick, only doing so when something about the item frame changes (metadata packet / clicked / loaded). Also a minor optimization of caching the output of getViewers() that speeds up a tiny bit too.

https://ci.mg-dev.eu/job/BKCommonLib/465/

**Comment by Duetro** [comment]
Thank you! It's way better now (3% -> 0.86%).
Timings with 1.13.2-v1-SNAPSHOT: https://s.duetro.de/i/firefox_2018-11-24_16-48-02.png
