### ISSUE TITLE
member not found

### ISSUE THREAD

**Issue by seema84** [bergerhealer/BKCommonLib#55]
BkCommonLib version: #4​77 
Spigot version: 1.13.2-R0.1-SNAPSHOT

[Server thread/INFO]: [BKCommonLib] Loading BKCommonLib v1.13.2-v1-SNAPSHOT
[Server thread/WARN]: A class member of net.minecraft.server.v1_13_R2.PacketPlayInSettings was not found!
[Server thread/WARN]: Failed to find field private int view:b; - Alternatives:
[Server thread/WARN]:   - private int e;
[Server thread/WARN]:   - private boolean d;
[Server thread/WARN]:   - private String a;
[Server thread/WARN]:   - private EntityHuman.EnumChatVisibility c;
[Server thread/WARN]:   - private EnumMainHand f;
[Server thread/WARN]:   - public int viewDistance;
[Server thread/WARN]: Field 'view' not found in template for net.minecraft.server.v1_13_R2.PacketPlayInSettings

**Comment by bbayu123** [comment]
Please check whether the latest build of BKCommonLib has fixed the issue.

**Comment by seema84** [comment]
thats true i close this issue
