### ISSUE TITLE
<bug> horrible tps

### ISSUE THREAD

**Issue by madtomic** [bergerhealer/BKCommonLib#58]
Please fix this.

**Comment by djbenbe** [comment]
![image](https://user-images.githubusercontent.com/12442307/52282570-02f9c280-2961-11e9-8099-ef0b34864b04.png)
which version do you have of bkc?
what I do not have this problem

**Comment by madtomic** [comment]
I am using latest version.

**Comment by madtomic** [comment]
it went from 19.9 to 14.xx in matters of minutes.

**Comment by djbenbe** [comment]
you have different version do /train version

**Comment by bergerkiller** [comment]
This is an issue ticket for BKCommonLib, but what plugin is using that library? BKCommonLib by itself does as little as possible, and previous 'issues' with tps were related to the framed map updater, in the <2% tps scale.

Is this with traincarts? A different plugin?

Timings would also be very helpful here. Use /timings start, let it run for a little while, then /timings paste.

**Comment by madtomic** [comment]
Light Cleaner is the issue.

**Comment by madtomic** [comment]
recreate issue
