### ISSUE TITLE
"TileEntity is in Entity List!" Spam

### ISSUE THREAD

**Issue by RyanHecht** [bergerhealer/BKCommonLib#6]
Ever since the initial 1.8 build, my console constantly gets spammed with a warning message: "TileEntity is in Entity List!" ...this may be logged tens of thousands of times (I think 50,000 is the most I've seen from one instance).

**Comment by mg-1999** [comment]
Update your BKC version, it is fixed it later releases.

**Comment by FriwiDev** [comment]
Yeah, I agree to what mg-1999 said. #closed

**Comment by RyanHecht** [comment]
Whoops, I'm just an idiot who can't read version numbers correctly
