### ISSUE TITLE
no such class: BlockPosition$b when load Train_Carts plugin

### ISSUE THREAD

**Issue by koenrousseau** [bergerhealer/BKCommonLib#62]
##### Spigot version: 1.13.2

Train_Carts-1.13.2-v1.jar

openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4, mixed mode)

<hr>

#### Problem or bug:

When I start the server, or when I try to reload the Train_Carts plugin (1.13.2-v1), I get this error message:

java.lang.RuntimeException: An exception occurred
Caused by: compile error: no such class: BlockPosition$b

#### Expected behaviour:

Would like to use the Train Carts plugin on 1.13.2.

#### Steps to reproduce:

Start a spigot server using the above plugin versions.

**Comment by weeryan17** [comment]
try this version of bkcommonlib https://ci.mg-dev.eu/job/BKCommonLib/532/artifact/target/BKCommonLib-1.13.2-v3-SNAPSHOT.jar

**Comment by koenrousseau** [comment]
Works, fantastic!
