### ISSUE TITLE
[SNAPSHOT-549] Error on registry

### ISSUE THREAD

**Issue by ironleather** [bergerhealer/BKCommonLib#63]
It force the console to disable the plugin to this error.

Plugin: BKCommonLibs 1.14.1 v1 SNAPSHOT-549
Server: PaperSpigot 20 (1.14.1)

This is what I see on console:
[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type SNOWBALL

java.lang.NullPointerException: null

at net.minecraft.server.v1_14_R1.EntityLiving.<init>(EntityLiving.java:3251) ~[patched_1.14.1.jar:git-Paper-20]

at net.minecraft.server.v1_14_R1.EntityArmorStand.<init>(EntityArmorStand.java:54) ~[patched_1.14.1.jar:git-Paper-20]

at net.minecraft.server.v1_14_R1.EntityTypes$$Lambda$606.000000004D127AD0.create(Unknown Source) ~[?:?]

at net.minecraft.server.v1_14_R1.EntityTypes.a(EntityTypes.java:295) ~[patched_1.14.1.jar:git-Paper-20]

at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedCodeInvoker$mplgen76852c3e.invoke(GeneratedCodeInvoker$mplgen76852c3e.java) ~[?:?]

at com.bergerkiller.mountiplex.reflection.util.FastMethod.invoke(FastMethod.java:122) ~[?:?]

at com.bergerkiller.bukkit.common.internal.logic.EntityTypingHandler_1_14.getClassFromEntityTypes(EntityTypingHandler_1_14.java:136) ~[?:?]

at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedCodeInvoker$mplgen4ee3e771.invoke_ub(GeneratedCodeInvoker$mplgen4ee3e771.java) ~[?:?]

at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedCodeInvoker$mplgen4ee3e771.invoke(GeneratedCodeInvoker$mplgen4ee3e771.java) ~[?:?]

at com.bergerkiller.mountiplex.reflection.util.FastMethod.invoke(FastMethod.java:122) ~[?:?]

at com.bergerkiller.mountiplex.reflection.declarations.Template$StaticMethod.invoke(Template.java:1265) ~[?:?]

at com.bergerkiller.generated.net.minecraft.server.EntityTypesHandle.getEntityTypeId(EntityTypesHandle.java:35) ~[?:?]

at com.bergerkiller.bukkit.common.entity.CommonEntityType.<init>(CommonEntityType.java:186) ~[?:?]

at com.bergerkiller.bukkit.common.entity.CommonEntityType.<clinit>(CommonEntityType.java:399) ~[?:?]

at java.lang.Class.forNameImpl(Native Method) ~[?:1.8.0_212]

at java.lang.Class.forName(Class.java:333) ~[?:1.8.0_212]

at com.bergerkiller.bukkit.common.Common.loadClasses(Common.java:307) ~[?:?]

at com.bergerkiller.bukkit.common.internal.CommonClasses.loadCommon(CommonClasses.java:56) ~[?:?]

at com.bergerkiller.bukkit.common.internal.CommonClasses.init(CommonClasses.java:33) ~[?:?]

at com.bergerkiller.bukkit.common.internal.CommonPlugin.onLoad(CommonPlugin.java:363) ~[?:?]

at org.bukkit.craftbukkit.v1_14_R1.CraftServer.loadPlugins(CraftServer.java:357) ~[patched_1.14.1.jar:git-Paper-20]

at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:216) ~[patched_1.14.1.jar:git-Paper-20]

at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:843) ~[patched_1.14.1.jar:git-Paper-20]

at java.lang.Thread.run(Thread.java:813) [?:1.8.0_212]

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type FIREBALL

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type SMALL_FIREBALL

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type ENDER_PEARL

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type ENDER_SIGNAL

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type SPLASH_POTION

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type THROWN_EXP_BOTTLE

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type ITEM_FRAME

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type WITHER_SKULL

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type PRIMED_TNT

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type FALLING_BLOCK

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type FIREWORK

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type HUSK

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type SPECTRAL_ARROW

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type SHULKER_BULLET

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type DRAGON_FIREBALL

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type ZOMBIE_VILLAGER

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type SKELETON_HORSE

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type ZOMBIE_HORSE

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type ARMOR_STAND

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type DONKEY

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type MULE

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type EVOKER_FANGS

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type EVOKER

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type VEX

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type VINDICATOR

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type ILLUSIONER

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type MINECART_COMMAND

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type BOAT

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type MINECART

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type MINECART_CHEST

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type MINECART_FURNACE

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type MINECART_TNT

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type MINECART_HOPPER

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type MINECART_MOB_SPAWNER

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type CREEPER

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type SKELETON

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type SPIDER

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type GIANT

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type ZOMBIE

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type SLIME

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type GHAST

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type PIG_ZOMBIE

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type ENDERMAN

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type CAVE_SPIDER

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type SILVERFISH

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type BLAZE

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type MAGMA_CUBE

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type ENDER_DRAGON

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type WITHER

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type BAT

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type WITCH

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type ENDERMITE

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type GUARDIAN

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type SHULKER

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type PIG

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type SHEEP

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type COW

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type CHICKEN

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type SQUID

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type WOLF

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type MUSHROOM_COW

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type SNOWMAN

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type OCELOT

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type IRON_GOLEM

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type HORSE

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type RABBIT

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type POLAR_BEAR

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type LLAMA

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type LLAMA_SPIT

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type PARROT

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type VILLAGER

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type ENDER_CRYSTAL

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type TURTLE

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type PHANTOM

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type TRIDENT

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type COD

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type SALMON

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type PUFFERFISH

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type TROPICAL_FISH

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type DROWNED

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type DOLPHIN

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type CAT

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type PANDA

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type PILLAGER

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type RAVAGER

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type TRADER_LLAMA

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type WANDERING_TRADER

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type FOX

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type FISHING_HOOK

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type LIGHTNING

[ERROR] [BKCommonLib.Registry] [BKCommonLib] [Registry] Failed to register entity type PLAYER

[ERROR] [org.bukkit.craftbukkit.v1_14_R1.CraftServer] com.bergerkiller.bukkit.common.conversion.DuplexConversion (initialization failure) initializing BKCommonLib v1.14.1-v1-SNAPSHOT (Is it up to date?)

**Comment by John067** [comment]
today, Bkcommonlib work just with spigot because some api are modified in paper
