### ISSUE TITLE
Plugin will not load on startup. 

### ISSUE THREAD

**Issue by ironik42** [bergerhealer/BKCommonLib#64]
##### Spigot version: git-Spigot-01d0f04-b7fea42 (MC: 1.14.2)

<hr>

**Comment by weeryan17** [comment]
1.14.2 support isn't a thing yet. use 1.14.1 if you want to run a 1.14 server with bkcommonlib

**Comment by Andre601** [comment]
I don't think this is up to date anymore since latest dev build seems to run on 1.14.2

**Comment by Tsoccerguy3** [comment]
does not load on 1.14.3

**Comment by bbayu123** [comment]
1.14.3 is not supported.

**Comment by Andre601** [comment]
> does not load on 1.14.3

That's because it's not yet supported... duh.

**Comment by bbayu123** [comment]
cuz... it's not resolved yet?

**Comment by Tsoccerguy3** [comment]
should close this issue as fixed
