### ISSUE TITLE
Error Spam minecraft:command_block 1.14

### ISSUE THREAD

**Issue by thunderlight411** [bergerhealer/BKCommonLib#65]
##### Spigot version:git-Paper-74

<hr>

#### Problem or bug: After upgrading world from 1.13.2 to 1.14.2 the console is getting spammed with a lot of error's about "Failed to load data for block entity minecraft:command_block"

When i disable both BKCommonLib and TrainCarts my console is clean and i don't get any error messages.

Trains are working "perfectly" as far i can see. Only console is getting spammed

see https://pastebin.com/HLJzGJrW for information

**Comment by bergerkiller** [comment]
Since this commit in BKCommonLib this issue is fixed: https://github.com/bergerhealer/BKCommonLib/commit/f716b166975381554db313c4ce1c818f3b7f6985
