### ISSUE TITLE
executing the command  /cleanlight world , on 1.14.3 on Paper 120 causes error

### ISSUE THREAD

**Issue by Tsoccerguy3** [bergerhealer/BKCommonLib#66]
##### BkCommonLib version:
BKCommonLib-1.14.3-v1-SNAPSHOT
##### Spigot version:
Paper 1.14.3 build 120
<hr>

#### Problem or bug:
3:28:17 AM [INFO] The world is now being fixed, this may take very long!
3:28:17 AM [INFO] To view the fixing status, use /cleanlight status
3:28:17 AM [SEVERE] [REFLECTION] Failed to compile method body ([source error] no such class: org.bukkit.craftbukkit.libs.it.unimi.dsi.fastutil.longs.LongSet):
3:28:17 AM [SEVERE] [REFLECTION] public Object invoke(Object instance_raw, Object world_raw) {net.minecraft.server.v1_14_R1.WorldServer world=(net.minecraft.server.v1_14_R1.WorldServer) world_raw;{
3:28:17 AM     ChunkProviderServer cps = world.getChunkProvider();
3:28:17 AM     PlayerChunkMap pcm = cps.playerChunkMap;
3:28:17 AM     RegionFileCache rfc = (RegionFileCache) pcm;
3:28:17 AM     org.bukkit.craftbukkit.libs.it.unimi.dsi.fastutil.longs.LongSet coordSet;
3:28:17 AM     org.bukkit.craftbukkit.libs.it.unimi.dsi.fastutil.longs.LongIterator iter;
3:28:17 AM     coordSet = rfc.cache.keySet();
3:28:17 AM     java.util.ArrayList result = new java.util.ArrayList(coordSet.size());
3:28:17 AM     iter = coordSet.iterator();
3:28:17 AM     while (iter.hasNext()) {
3:28:17 AM         long coord = iter.nextLong();
3:28:17 AM         int coord_x = ChunkCoordIntPair.getX(coord);
3:28:17 AM         int coord_z = ChunkCoordIntPair.getZ(coord);
3:28:17 AM         result.add(new com.bergerkiller.bukkit.common.bases.IntVector2(coord_x, coord_z));
3:28:17 AM     }
3:28:17 AM     return result;
3:28:17 AM }
3:28:17 AM return null;}
3:28:17 AM [SEVERE] [BKCommonLib] [BKCommonLib] Unhandled exception executing command 'cleanlight' in plugin LightCleaner v1.14.2-v1-SNAPSHOT
3:28:17 AM [WARNING] java.lang.RuntimeException: An exception occurred
3:28:17 AM [WARNING] Caused by: compile error: no such class: org.bukkit.craftbukkit.libs.it.unimi.dsi.fastutil.longs.LongSet
3:28:17 AM [WARNING] 	at com.bergerkiller.mountiplex.dep.javassist.compiler.MemberResolver.searchImports(MemberResolver.java:479)
3:28:17 AM [WARNING] 	at com.bergerkiller.mountiplex.dep.javassist.compiler.MemberResolver.lookupClass(MemberResolver.java:422)
3:28:17 AM [WARNING] 	at com.bergerkiller.mountiplex.dep.javassist.compiler.MemberResolver.lookupClassByJvmName(MemberResolver.java:329)
3:28:17 AM [WARNING] 	at com.bergerkiller.mountiplex.dep.javassist.compiler.MemberResolver.resolveJvmClassName(MemberResolver.java:519)
3:28:17 AM [WARNING] 	at com.bergerkiller.mountiplex.dep.javassist.compiler.MemberCodeGen.resolveClassName(MemberCodeGen.java:1190)
3:28:17 AM [WARNING] 	at com.bergerkiller.mountiplex.dep.javassist.compiler.CodeGen.atDeclarator(CodeGen.java:757)
3:28:17 AM [WARNING] 	at com.bergerkiller.mountiplex.dep.javassist.compiler.ast.Declarator.accept(Declarator.java:103)
3:28:17 AM [WARNING] 	at com.bergerkiller.mountiplex.dep.javassist.compiler.CodeGen.atStmnt(CodeGen.java:381)
3:28:17 AM [WARNING] 	at com.bergerkiller.mountiplex.dep.javassist.compiler.ast.Stmnt.accept(Stmnt.java:53)
3:28:17 AM [WARNING] 	at com.bergerkiller.mountiplex.dep.javassist.compiler.CodeGen.atStmnt(CodeGen.java:381)
3:28:17 AM [WARNING] 	at com.bergerkiller.mountiplex.dep.javassist.compiler.ast.Stmnt.accept(Stmnt.java:53)
3:28:17 AM [WARNING] 	at com.bergerkiller.mountiplex.dep.javassist.compiler.CodeGen.atStmnt(CodeGen.java:381)
3:28:17 AM [WARNING] 	at com.bergerkiller.mountiplex.dep.javassist.compiler.ast.Stmnt.accept(Stmnt.java:53)
3:28:17 AM [WARNING] 	at com.bergerkiller.mountiplex.dep.javassist.compiler.CodeGen.atMethodBody(CodeGen.java:321)
3:28:17 AM [WARNING] 	at com.bergerkiller.mountiplex.dep.javassist.compiler.CodeGen.atMethodDecl(CodeGen.java:303)
3:28:17 AM [WARNING] 	at com.bergerkiller.mountiplex.dep.javassist.compiler.ast.MethodDecl.accept(MethodDecl.java:47)
3:28:17 AM [WARNING] 	at com.bergerkiller.mountiplex.dep.javassist.compiler.Javac.compileMethod(Javac.java:175)
3:28:17 AM [WARNING] 	at com.bergerkiller.mountiplex.dep.javassist.compiler.Javac.compile(Javac.java:102)
3:28:17 AM [WARNING] 	at com.bergerkiller.mountiplex.dep.javassist.CtNewMethod.make(CtNewMethod.java:79)
3:28:17 AM [WARNING] 	at com.bergerkiller.mountiplex.dep.javassist.CtNewMethod.make(CtNewMethod.java:50)
3:28:17 AM [WARNING] 	at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedCodeInvoker.makeMethodAndLog(GeneratedCodeInvoker.java:87)
3:28:17 AM [WARNING] 	at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedCodeInvoker.create(GeneratedCodeInvoker.java:312)
3:28:17 AM [WARNING] 	at com.bergerkiller.mountiplex.reflection.util.FastMethod$FastMethodInitProxy.init(FastMethod.java:168)
3:28:17 AM [WARNING] 	at com.bergerkiller.mountiplex.reflection.util.FastMethod$FastMethodInitProxy.invoke(FastMethod.java:191)
3:28:17 AM [WARNING] 	at com.bergerkiller.mountiplex.reflection.util.FastMethod.invoke(FastMethod.java:122)
3:28:17 AM [WARNING] 	at com.bergerkiller.bukkit.common.internal.logic.RegionHandler_1_14.getRegions(RegionHandler_1_14.java:99)
3:28:17 AM [WARNING] 	at com.bergerkiller.bukkit.common.utils.WorldUtil.getWorldRegions(WorldUtil.java:1006)
3:28:17 AM [WARNING] 	at com.bergerkiller.bukkit.lightcleaner.util.RegionInfoMap.create(RegionInfoMap.java:63)
3:28:17 AM [WARNING] 	at com.bergerkiller.bukkit.lightcleaner.lighting.LightingTaskWorld.<init>(LightingTaskWorld.java:17)
3:28:17 AM [WARNING] 	at com.bergerkiller.bukkit.lightcleaner.lighting.LightingService.schedule(LightingService.java:169)
3:28:17 AM [WARNING] 	at com.bergerkiller.bukkit.lightcleaner.lighting.LightingService.scheduleWorld(LightingService.java:128)
3:28:17 AM [WARNING] 	at com.bergerkiller.bukkit.lightcleaner.LightCleaner.command(LightCleaner.java:108)
3:28:17 AM [WARNING] 	at com.bergerkiller.bukkit.common.PluginBase.onCommand(PluginBase.java:894)
3:28:17 AM [WARNING] 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
3:28:17 AM [WARNING] 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
3:28:17 AM [WARNING] 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:736)
3:28:17 AM [WARNING] 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchServerCommand(CraftServer.java:698)
3:28:17 AM [WARNING] 	at net.minecraft.server.v1_14_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:459)
3:28:17 AM [WARNING] 	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:421)
3:28:17 AM [WARNING] 	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1064)
3:28:17 AM [WARNING] 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:908)
3:28:17 AM [WARNING] 	at java.lang.Thread.run(Unknown Source)
3:28:17 AM [INFO] An internal error occured while executing this command

#### Expected behaviour:
to clean map of light glitches 
#### Steps to reproduce:
enter /cleanlight world or /cleanlight world "name of map" or /cleanlight "any number"

**Comment by Tsoccerguy3** [comment]
https://github.com/bergerhealer/Light-Cleaner/issues/11#issuecomment-507163327

**Comment by bergerkiller** [comment]
LongHashSet is a remapping of some other library class. Maybe the class was moved in 1.14.3. I'll look into it later tonight

**Comment by bergerkiller** [comment]
This should fix it. https://github.com/bergerhealer/BKCommonLib/commit/0771a12f1c2b00f3161e7443e8271bfe59d06ba5

https://ci.mg-dev.eu/job/BKCommonLib/565/

**Comment by Tsoccerguy3** [comment]
Fixed , closing
