### ISSUE TITLE
Scoreboard

### ISSUE THREAD

**Issue by Mexicaantjes** [bergerhealer/BKCommonLib#7]
Scoreboard API doesn't work

**Comment by mg-1999** [comment]
That is said on the bkcommonlib download page. We disabled it because we
didn't had the time to update it in time for release.

Op zo 7 feb. 2016 11:54 schreef Mexicaantjes <notifications@github.com>:

> Scoreboard API doesn't work
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bergerhealer/BKCommonLib/issues/7>.
>
-- 

Met vriendelijk groeten,

Matthijs Giezenberg
