### ISSUE TITLE
Do you have some will to fix BkCommonLib for KCauldron/Thermos 1.7.10?

### ISSUE THREAD

**Issue by vpontin** [bergerhealer/BKCommonLib#8]
##### Spigot version: KCauldron/Thermos 1.7.10

<hr>

So, just this question. Seems like "the killer" disappeared before fix this bit for us. I know its like a stupidity to keep with 1.7.x, but given the conditions of the community after the Wolverness DCMA, [KCauldron](https://gitlab.prok.pw/Prototik/KCauldron) and [Thermos](https://github.com/TCPR/Thermos/) still keeps the last tie between forge and spigot.

**Comment by mg-1999** [comment]
I would like to fix it. But 1.9 is out in a few days and I see no reason to support a 2 year old version.

**Comment by vpontin** [comment]
Well, due to DCMA fuss, the uniqueness of KCauldron (at the moment) and the slowness to having a Sponge stable release, most of the people (like me) are still sticked in 1.7.10.

Perharps you can only do the fix as a symbolic way to end the 1.7.10 lifecycle (we never had a stable version for both mods in Cauldron at this version). But its up to you.

Anyway, sorry for the text fuzz (english isnt my home language) and thanks for the awesome work of keeping BKCommonLib and TrainCarts alive.

**Comment by mg-1999** [comment]
Maybe when I have some spare freetime I will give it a try, but we are currently focusing on the 1.9 update

**Comment by vpontin** [comment]
Thank you so much for this! I will wait patiently for this happen!

**Comment by vpontin** [comment]
A last information: Seems like after some time inactivy, @Yive started a fork called THERMOS:
https://github.com/TCPR/Thermos

I dont know how long this repository will stay on Github due to Wolverness copyright, but seems like this fork is more actively updated than the original KCauldron, so maybe you can test the plugin against this one instead.

**Comment by mg-1999** [comment]
@vpontin I will look into it. First some things for 1.9 need to be fixed.

**Comment by Bogdan-G** [comment]
@vpontin DCMA has long been withdrawn

**Comment by vpontin** [comment]
Really? Where did you get that news from?

**Comment by Bogdan-G** [comment]
@vpontin I read about it over a year ago

**Comment by vpontin** [comment]
Well, seems like @vrackfall are trying to fix yourself BKCommonLib and other plugins. Instead of deraliling this issue with unrelated content, maybe he can use it to say your troubles trying to update or helping @mg-1999 to fix too.

**Comment by NDruce** [comment]
I don't understand, will be it fixed or not)

**Comment by vpontin** [comment]
They only will think about fix AFTER fixing all 1.9 bugs (for spigot)

**Comment by vrackfall** [comment]
I tried to fix the 1.7.10 version of BKCOmmonLib to cauldron 1.7.10, but it's not working for now sorry

**Comment by NDruce** [comment]
I started porting it, for now everything is going well! But it about 74 classes remaining porting... I hate this, even it 100% will work :)

**Comment by mg-1999** [comment]
You are awesome @NDruce !

**Comment by NDruce** [comment]
I've started new repo: https://github.com/NDruce/BKCommonLib-Thermos
Follow work progress in README.md, I will do release when done ;)

**Comment by mg-1999** [comment]
I can add the repo to our page if you want to? Makes it easier to find for
all of us.

Op zo 5 jun. 2016 23:26 schreef NDruce <notifications@github.com>:

> I've started new repo: https://github.com/NDruce/BKCommonLib-Thermos
> Follow work progress in README.md, I will do release when done ;)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/bergerhealer/BKCommonLib/issues/8#issuecomment-223838744>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AGmkdu5qa1xGnyPgWF5tf-48IbnszK8lks5qIz8DgaJpZM4Hg8TJ>
> .
>
-- 

Met vriendelijk groeten,

Matthijs Giezenberg

**Comment by NDruce** [comment]
Ok

**Comment by mg-1999** [comment]
You should push all your code, and not just the readme.

**Comment by NDruce** [comment]
https://www.youtube.com/watch?v=ZSJ8Rnz58Ck

**Comment by mg-1999** [comment]
Why didn't you put the source on github? Makes it way easier for all of us.

Op za 11 jun. 2016 17:27 schreef NDruce <notifications@github.com>:

> https://www.youtube.com/watch?v=ZSJ8Rnz58Ck
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/bergerhealer/BKCommonLib/issues/8#issuecomment-225369874>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AGmkdgL9-wNanr6x520Fyn8YiW-sf-U6ks5qKtPRgaJpZM4Hg8TJ>
> .
>
-- 

Met vriendelijk groeten,

Matthijs Giezenberg

**Comment by vpontin** [comment]
Closing. See https://github.com/CyberdyneCC/Thermos/issues/268
