### ISSUE TITLE
Lag spikes caused by CachedMapItemCleaner

### ISSUE THREAD

**Issue by mibby** [bergerhealer/BKCommonLib#90]
##### Spigot version: Purpur dev 495

I seem to be getting some tps spikes / random drops caused by BKCommonLib's CachedMapItemCleaner. :( The only BKCommonLib plugin I have installed is LightCleaner.

![link](https://i.imgur.com/3KtEYYP.png)

**Comment by bergerkiller** [comment]
That would require somebody having used at least 1000 different map items in creative mode the last 10 minutes, which would be unlikely but just in case you have a clue I'll mention it.

That task runs every minute.

Do you have a link to the full timings? They may help me track down other hotspots that are really to blame, like onCreativeItemSet

**Comment by bergerkiller** [comment]
Actually, why is the run count of that task 31433 while the server itself has ticked 878 times? Did you use /reload?

**Comment by mibby** [comment]
I did not use a reload and no one ever should (😢). The timings was taken shortly after a server restart and only profiled for a short duration (82 seconds to try and find the cause of some spikes). 

Here is the full report.
https://timings.pl3x.net/?id=2f020b51fdf044d9ab935baa2f0b7211#timings

The logging period graph doesn't show the TPS instability, but TPS was jumping all over the place. 20 > 19.3 > 20 > 19.7 > 20 > 19.6, etc. etc.

Perhaps it is conflicting with various map plugins like ArtMap and BannerBoard, both of which are used to load and display images on maps / draw on map? It may load all maps at start-up and cache them for ease of access / sorting.

I can do some more short duration burst profiles and WarmRoast profiles if needed.

**Comment by bergerkiller** [comment]
Something really strange is going on. When I look at the timings in detail, that same task that shows up high on the main timings page as litterally 0.0% on the BKCommonLib plugin-specific tab. Is this a bug in the timings profiler?

I think the best thing you can do is run a spark profiler cpu sampler run for a couple minutes so I can see more precisely where your tps drops are coming from. Strange, first time I see a glitch in the timings library

**Comment by bergerkiller** [comment]
![ScreenShot 2020-03-20 18 19 40](https://user-images.githubusercontent.com/957601/77189118-5f716000-6ad7-11ea-9f43-007343a84acd.jpg)
![ScreenShot_2020-03-20 18-20-02](https://user-images.githubusercontent.com/957601/77189159-6c8e4f00-6ad7-11ea-860c-5078191375d3.png)

**Comment by mibby** [comment]
Very odd. I'll run a Spark profile later tonight to see what I can measure.

@BillyGalbreath Bug in timings report?

**Comment by mibby** [comment]
Here is a 60s Spark profile of all threads.
https://sparkprofiler.github.io/#GWfjBPfKL7

**Comment by bergerkiller** [comment]
Spark profiler shows that on average everything is fine at least, which means it has to be lag pulses that occur occasionally and not continuously. I hoped to see something there but unfortunately it's not very good at identifying lag spikes, since all it shows is an average.

In the original timings report though, if I can trust the by-plugin tab, I do see that 'ButtonWarp' has quite a high lag spike going on. If I judge its functionality and it spending time in 'sync chunk loading', I assume it's from players teleporting to a destination and the plugin pre-loading the entire chunk area at the destination up-front.

Might be worth checking out

**Comment by mibby** [comment]
I'll definitely look into ButtonWarps. Just ufortunately it has stopped receiving updates many years ago and there are no real good alternatives that have the same functionality and features of it.

The plugins tab I wasn't too worried about because it doesn't seem to be that much lag for the whole report duration. I was just more curious as to why BKCommonLib was showing so heavily under the bukkit scheduler. :(

**Comment by bergerkiller** [comment]
You can probably get around the lag from buttonwarp if you keep the destination area loaded using a different chunk loader plugin. That way it won't have to load the large chunk area in a single tick each time a player teleports

**Comment by bergerkiller** [comment]
@mibby any update on this situation? Wat it buttonwarp or is this possibly still related to BKCommonLib?

**Comment by mibby** [comment]
ButtonWarp was not the cause of BKCommonLib's timings. I'm unfortunately still able to get BKCommonLib to show up high in timing reports.

What would be nice is if there was a way to only enable specific BKCommonLib events so you can have only what you need enabled instead of ticking / listening for everything. In my case, I only use LightCleaner.

**Comment by bergerkiller** [comment]
Programmatically, for most things, that is already the case. If plugins don't use it, it's not enabled. With map displays it's a little more difficult because you don't know up front whether there are items in the world that load some map display class. Plugins don't register that.

Can you try to make one more timings report that shows this? I can add something to BKC's config file to disable some aspect of it, so you can check whether it helps or not. Just got to confirm what part I need to disable.

**Comment by mibby** [comment]
Here is a quick report. While not as egregious in numbers as the earlier timings above, it shows BKCommonLib at the very top above all "plugin considered" lag.

![link-new](https://i.imgur.com/VytJrFq.png)
https://timings.pl3x.net/?id=f3d70ecff10047218c855ffc250db544

CachedMapItemCleaner still hits me pretty hard as well, but it is only during server initialization when all the map plugins I have begin to load. (ArtMap / BannerBoard) I'll have to get you an early start-up timings after I push some updates.

**Comment by bergerkiller** [comment]
So all issues so far have been caused by the map display api part of bkcommonlib? Because then I'll just add one global toggle for all that.

**Comment by mibby** [comment]
As far as I've seen, yes.

**Comment by bergerkiller** [comment]
Alright, pushed a commit. https://github.com/bergerhealer/BKCommonLib/commit/d216cd3f25b3efa0f05158f12ae440c256779aaf

```
#> This is the main configuration file of BKCommonLib
#> Normally you should not have to make changes to this file
#> Unused components of the library can be disabled to improve performance
#> By default all components and features are enabled

# Whether multiple item frames next to each other can merge to show one large display
# This allows Map Displays to be displayed on multiple item frames at a larger resolution
# The tiling detection logic poses some overhead on the server, and if unused, can be disabled
enableItemFrameTiling: true

# Whether the Map Display engine is enabled, running in the background to refresh and render maps
# When enabled, the map item tracking may impose a slight overhead
# If no plugin is using map displays, then this can be safely disabled to improve performance
enableMapDisplays: true```

https://ci.mg-dev.eu/job/BKCommonLib/742/

**Comment by mibby** [comment]
The new setting seems to work great! BKCommonLib is not in the timings report anymore and what _is_ shown (EntityRemovalHandler/TabUpdater/MoveEventHandler) is practically non-existent.

**Comment by bergerkiller** [comment]
Good to hear! Unfortunate that the passive mapdisplay logic can show up so high, though it might in part be because there's nothing else interesting going on that plugins are doing. So relatively speaking, bkc is doing a lot.

It's an ongoing effort to reduce wasted time in areas like this, but disabling it all is the ultimate optimization :p
