### ISSUE TITLE
Warning while changing maps in itemframes

### ISSUE THREAD

**Issue by csev98** [bergerhealer/BKCommonLib#93]
##### Spigot version: Paper 260

<hr>

#### Problem or bug:
When changing maps in itemframes I receive the following warning multiple times in my console:
[https://pastebin.com/RQAW3H8r](https://pastebin.com/RQAW3H8r)

I'm not using bkcommonlib for changing the maps or spawning itemframes. I simply use the following code:
`ItemFrame frame = ...;`
`frame.setItem(itemstack);`

**Comment by bergerkiller** [comment]
Could confirm that one, did a quick fix but you'll have to verify it silenced the errors. https://ci.mg-dev.eu/job/BKCommonLib/780/

**Comment by csev98** [comment]
Yes, it is fixed. Thank you
