### ISSUE TITLE
Failed to register static converter method

### ISSUE THREAD

**Issue by ShadowChildUK** [bergerhealer/BKCommonLib#95]
##### Spigot version: Paper 1.8.8

<hr>

**Comment by bergerkiller** [comment]
Very strange, an error deep inside the JVM itself. What java version does the server use? I can find some information about this error online, but they point to an error involving lambdas.

Just in case this can be easily fixed this way: try running on a very recent java (for example, JDK 13) and see if these issues persist. I can try to add a workaround in mountiplex catching this error if that doesn't help.

**Comment by ShadowChildUK** [comment]
> Very strange, an error deep inside the JVM itself. What java version does the server use? I can find some information about this error online, but they point to an error involving lambdas.
> 
> Just in case this can be easily fixed this way: try running on a very recent java (for example, JDK 13) and see if these issues persist. I can try to add a workaround in mountiplex catching this error if that doesn't help.

The server is on Java 8. Unfortunately, as I'm sure you're aware MC1.8 doesn't support any java > 8

**Comment by bergerkiller** [comment]
I just ran Spigot 1.8 on Java 11 and this worked fine. Where did you get this information?

**Comment by bergerkiller** [comment]
I can't guarantee this fixes things, but it's worth a try. https://ci.mg-dev.eu/job/BKCommonLib/792/

**Comment by ShadowChildUK** [comment]
> I just ran Spigot 1.8 on Java 11 and this worked fine. Where did you get this information?

Spigot probably will, Paper however does not. I'll try the fix once the build is finished and report back here

**Comment by ShadowChildUK** [comment]
> I can't guarantee this fixes things, but it's worth a try. https://ci.mg-dev.eu/job/BKCommonLib/792/

No fix. Same errors.

**Comment by bergerkiller** [comment]
What errors? Because I catch the error you posted, so what you got now has to be different

**Comment by ShadowChildUK** [comment]
> What errors? Because I catch the error you posted, so what you got now has to be different. It might help to run Paper 1.8 myself, but it's not available for download. How did you build it?

Exactly the same errors https://hastebin.com/zufapuhelu.md It's available [here](https://serverjars.com/jars/servers/paper/paper-1.8.8.jar)

**Comment by bergerkiller** [comment]
Ok try 2. Same error, different location and method. https://ci.mg-dev.eu/job/BKCommonLib/793/

Thanks for the link, Ill run it myself too to see what I get

**Comment by ShadowChildUK** [comment]
Different errors; https://hastebin.com/yuwuwowelu.pl (the error is towards the bottom) @bergerkiller

**Comment by bergerkiller** [comment]
I'm kind of at a loss at this point, the java virtual machine isn't cooperating whatsoever. Methods being 'volatile' is extremely weird, and online searches for that result in people speaking about decompiler issues. I'm starting to think your server jar is corrupt somehow, or the one in your cache directory is at the very least. Again, I can run the paper you linked on JRE 1.8.0_221 just fine, but later versions work as well.

Why is this easy for you to reproduce but nothing happens here? There must be some detail I am missing.

When paper first boots up it downloads the minecraft server jar and patches it. This is the patched file it generated on my end (which works fine). What happens if you boot the server using that?

https://www.dropbox.com/s/q3mvqvldqdbr6kf/paper-1.8.8-cached.jar?dl=0

**Comment by RealGatt** [comment]
I can confirm that Paper does work with Java 11. We have multiple 1.8 servers running on Java 11. If you're using Pterodactyl, try using this Docker Container: 

quay.io/gravitas/pterodcatyl-jdk11-openj9-containers:adoptopenjdk-11-openj9

**Comment by bergerkiller** [comment]
@ShadowChildUK do you still have this issue? Or have since found out why the method modifiers are so different in your custom jar? I will reopen this if extra information / server jar to test with is provided.
