### ISSUE TITLE
java.java.lang.UnsupportedOperationException: Field net.minecraft.server.PacketPlayOutRespawn.dimension is not available

### ISSUE THREAD

**Issue by AegeanStudios** [bergerhealer/BKCommonLib#99]
##### Spigot version: PaperSpigot 1.16.1 Build 27

<hr>

#### Steps to reproduce: Using V1 snapshot of BK, and build 27 of paper, die and respawn by any means.

Sidenote: I understand that 1.16's version is still heavily in development, but i felt it neccesary to report the bug nevertheless.

**Comment by bergerkiller** [comment]
Yeah the dimension/worldtype/etc. fields are all nonfunctional at the moment. There's some ongoing work to replace them all, since they changed from an enumeration to a namespaced key.

**Comment by weeryan17** [comment]
If you find a bug like this in the 1.16 version please ask about it in the [support server](https://discord.gg/DAhNQaB) before making an issue report.
1.16 is currently very much unstable and bugs like this are already known. We don't need to clog up the issues reports with issues like this if we don't have to. I'm going to keep this open as it is still a valid issue, just please report 1.16 errors in discord in the future.

**Comment by bergerkiller** [comment]
This has since been fixed. Some old fields are no longer supported, but are also unused in the code. If there's a need to access those fields of the packet, people can make an issue ticket.
